"""The markdown overlay projection: the Live Index rendered back into the library.

For each configured library this writes plain, editor-facing markdown into
``<library_root>/<dirname>``: one note per indexed source (identity, provenance,
claim digest, a relative link to the source file), one dashboard per domain, and a
root index. The overlay sits inside the library but is never corpus — ``dirname``
must start with one of the library's exclude prefixes, so the Live Index walk
cannot see it, and :func:`write_overlay` refuses a dirname that would be indexed.

Like ``by-domain/``, the overlay is a projection that owns its directory: content
derives only from the materialized store (no wall-clock, sorted throughout), so an
unchanged store rewrites byte-identical files, stale files are removed, and the
whole directory may be deleted at any time and rebuilt.
"""
from __future__ import annotations

import csv
import posixpath
from pathlib import Path

from .sync import SyncState

OVERLAY_DIRNAME = "_overlay"
_BANNER = "Generated by the overlay projection — do not edit; regeneration replaces this directory."


def _domain_claims(kg_root: Path, domain: str) -> dict[str, list[dict]]:
    """Group one domain's claim rows by canonical URN, preserving extraction order."""
    path = kg_root / "by-domain" / domain / "claims.csv"
    grouped: dict[str, list[dict]] = {}
    if not path.exists():
        return grouped
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            grouped.setdefault(row.get("canonical_urn", ""), []).append(row)
    return grouped


def _note_relpath(relpath: str) -> str:
    return f"sources/{relpath}.md"


def _source_note(lib_id: str, relpath: str, entry: dict, claims: list[dict]) -> str:
    back = posixpath.relpath(relpath, posixpath.dirname(f"{OVERLAY_DIRNAME}/" + _note_relpath(relpath)))
    lines = [
        f"# {relpath}", "",
        f"- library: `{lib_id}`",
        f"- domain: `{entry.get('domain', '_root')}`",
        f"- canonical: `{entry.get('canonical_urn', '')}`",
        f"- content-sha1: `{entry.get('sha1', '')}`",
        f"- claims: {entry.get('n_claims', 0)}",
        f"- source file: [{relpath}]({back})",
        "", "## Claims", "",
    ]
    if claims:
        for row in claims:
            label = row.get("predicate") or row.get("type") or row.get("marker") or "claim"
            lines.append(f"- **{label}** — {row.get('text', '')}")
    else:
        lines.append("No claims extracted — this source carries identity and history only.")
    lines.append("")
    return "\n".join(lines)


def _domain_page(domain: str, rows: list[tuple[str, dict]]) -> str:
    total = sum(entry.get("n_claims", 0) for _, entry in rows)
    lines = [f"# Domain: {domain}", "",
             f"{len(rows)} sources · {total} claims", ""]
    for relpath, entry in rows:
        link = posixpath.relpath(_note_relpath(relpath), "domains")
        lines.append(f"- [{relpath}]({link}) — {entry.get('n_claims', 0)} claims")
    lines.append("")
    return "\n".join(lines)


def _index_page(lib_id: str, graph_version: str,
                domains: dict[str, list[tuple[str, dict]]]) -> str:
    sources = sum(len(rows) for rows in domains.values())
    claims = sum(entry.get("n_claims", 0)
                 for rows in domains.values() for _, entry in rows)
    lines = [f"# {lib_id} — overlay", "", _BANNER, "",
             f"- graph version: `{graph_version}`",
             f"- sources: {sources}",
             f"- claims: {claims}",
             "", "## Domains", ""]
    for domain, rows in sorted(domains.items()):
        total = sum(entry.get("n_claims", 0) for _, entry in rows)
        lines.append(f"- [{domain}](domains/{domain}.md) — {len(rows)} sources, {total} claims")
    lines.append("")
    return "\n".join(lines)


def _replace_directory(base: Path, files: dict[str, str]) -> dict:
    """Make ``base`` contain exactly ``files``; touch only paths whose bytes change."""
    written, unchanged = 0, 0
    for rel, content in sorted(files.items()):
        target = base / rel
        data = content.encode("utf-8")
        if target.exists() and target.read_bytes() == data:
            unchanged += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        written += 1
    removed = 0
    if base.exists():
        for p in sorted(base.rglob("*"), reverse=True):
            if p.is_file() and p.relative_to(base).as_posix() not in files:
                p.unlink()
                removed += 1
            elif p.is_dir() and not any(p.iterdir()):
                p.rmdir()
    return {"written": written, "unchanged": unchanged, "removed": removed}


def write_overlay(config: dict, dirname: str = OVERLAY_DIRNAME) -> dict:
    """Write the markdown overlay projection into each configured library root."""
    kg_root = Path(config["kg_root"])
    version_path = kg_root / "_graph_version.json"
    graph_version = ""
    if version_path.exists():
        import json
        graph_version = json.loads(version_path.read_text(encoding="utf-8")).get(
            "graph_version", "")
    state = SyncState(kg_root)
    report = {"kg_root": str(kg_root), "graph_version": graph_version, "libraries": []}
    for lib in config.get("libraries", []):
        lib_id = lib["id"]
        prefixes = tuple(lib.get("exclude_prefixes") or ())
        if not any(dirname.startswith(pfx) for pfx in prefixes):
            raise ValueError(
                f"overlay dirname {dirname!r} is not covered by the library's exclude "
                f"prefixes {list(prefixes)} — the Live Index would treat it as corpus")
        prefix = lib_id + "::"
        domains: dict[str, list[tuple[str, dict]]] = {}
        for key in sorted(state.files):
            if not key.startswith(prefix):
                continue
            relpath = key[len(prefix):]
            entry = state.files[key]
            domains.setdefault(entry.get("domain", "_root"), []).append((relpath, entry))
        files = {"index.md": _index_page(lib_id, graph_version, domains)}
        for domain, rows in domains.items():
            files[f"domains/{domain}.md"] = _domain_page(domain, rows)
            claims = _domain_claims(kg_root, domain)
            for relpath, entry in rows:
                files[_note_relpath(relpath)] = _source_note(
                    lib_id, relpath, entry, claims.get(entry.get("canonical_urn", ""), []))
        base = Path(lib["root_path"]) / dirname
        result = _replace_directory(base, files)
        report["libraries"].append({
            "id": lib_id, "overlay": str(base),
            "sources": sum(len(rows) for rows in domains.values()),
            "domains": len(domains), **result,
        })
    return report
