"""Universal language/system adapter protocol."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from versum.nd import NDSystem

from .intermediate import (
    AdapterCapabilities, ArtifactBundle, ExportResult, GraphProjection, SystemIdentity,
)


@runtime_checkable
class SystemAdapter(Protocol):
    """Boundary implemented by grammar, policy, schema, and runtime-system adapters."""

    def identity(self) -> SystemIdentity: ...
    def capabilities(self) -> AdapterCapabilities: ...
    def artifacts(self) -> ArtifactBundle: ...
    def nd_systems(self) -> tuple[NDSystem, ...]: ...
    def parse(self, source: str) -> Any: ...
    def validate_program(self, program: Any) -> dict: ...
    def project(self, program: Any) -> GraphProjection: ...
    def import_observation(self, value: dict) -> GraphProjection: ...
    def export(self, projection: GraphProjection) -> ExportResult: ...
